// routes/guides-admin.js
//
// Admin API + page for the Guide Editor — a full SEO-friendly rich
// text editor for the Knowledge Base.
//
// Saving a guide here writes TWO things:
//
//   1. public/guides/<slug>/index.html
//      A complete, standalone, server-rendered article page (title,
//      meta description, canonical link, Article structured data,
//      site nav/footer, and the article body) — generated by
//      lib/guide-page.js.
//
//   2. data/guides.json
//      The matching homepage "Knowledge Base" card (title, tagline,
//      description, category, url), read by lib/cards.js (SSR) and
//      public/script.js (client-side render).
//
// Visit /admin/guides to use the editor.
//
// SECURITY NOTE
// This router lets anyone who can reach it create/edit/delete guide
// pages and the homepage card list. It does NOT include
// authentication. Before deploying, protect it, e.g.:
//
//   router.use((req, res, next) => {
//     if (!req.session || !req.session.isAdmin) return res.sendStatus(401);
//     next();
//   });

const express = require('express');
const fs = require('fs');
const path = require('path');
const sanitizeHtml = require('sanitize-html');

const { renderGuidePage, extractBodyHtml } = require('../lib/guide-page');
const adminAuth = require('../lib/admin-auth');
const router = express.Router();
router.use('/admin/guides', adminAuth);
router.use('/api/admin/guides', adminAuth);
const GUIDES_DIR = path.join(__dirname, '..', 'public', 'guides');
const GUIDES_JSON = path.join(__dirname, '..', 'data', 'guides.json');
const SLUG_RE = /^[a-z0-9-]+$/i;

fs.mkdirSync(GUIDES_DIR, { recursive: true });

// ---- sanitization for article body HTML coming from the editor ----
const SANITIZE_OPTIONS = {
  allowedTags: [
    'p', 'br', 'hr',
    'strong', 'b', 'em', 'i', 'u', 's', 'sup', 'sub',
    'h2', 'h3', 'h4',
    'ul', 'ol', 'li',
    'a', 'img', 'figure', 'figcaption',
    'blockquote', 'code', 'pre',
    'table', 'thead', 'tbody', 'tr', 'th', 'td'
  ],
  allowedAttributes: {
    a: ['href', 'title', 'target', 'rel'],
    img: ['src', 'alt', 'title', 'width', 'height']
  },
  allowedSchemes: ['http', 'https', 'mailto'],
  // Drop empty paragraphs left over from contenteditable editing
  exclusiveFilter: (frame) => frame.tag === 'p' && !frame.text.trim() && !/<img|<br/.test(frame.innerHTML || ''),
  transformTags: {
    a: (tagName, attribs) => {
      const out = { tagName, attribs: { ...attribs } };
      if (out.attribs.target === '_blank') {
        out.attribs.rel = 'noopener noreferrer';
      }
      return out;
    }
  }
};

function sanitizeBodyHtml(html) {
  const clean = sanitizeHtml(String(html || ''), SANITIZE_OPTIONS);
  return clean.trim();
}

// ---- guides.json helpers ----
function readGuidesJson() {
  try {
    const raw = fs.readFileSync(GUIDES_JSON, 'utf8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (e) {
    return [];
  }
}

function writeGuidesJson(list) {
  fs.mkdirSync(path.dirname(GUIDES_JSON), { recursive: true });
  fs.writeFileSync(GUIDES_JSON, JSON.stringify(list, null, 2) + '\n', 'utf8');
}

function wordCount(html) {
  const text = String(html || '').replace(/<[^>]+>/g, ' ').replace(/&[a-z#0-9]+;/gi, ' ');
  const t = text.trim();
  return t ? t.split(/\s+/).length : 0;
}

function guidePagePath(slug) {
  return path.join(GUIDES_DIR, slug, 'index.html');
}

// ---- Admin page ----
router.get('/admin/guides', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'public', 'admin-guides.html'));
});

// ---- List all guides (union of public/guides/* pages and homepage cards) ----
router.get('/api/admin/guides', (req, res) => {
  let pageSlugs = [];
  try {
    pageSlugs = fs.readdirSync(GUIDES_DIR, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => fs.existsSync(guidePagePath(name)));
  } catch (e) {
    // directory missing is fine, treated as no pages yet
  }

  const cards = readGuidesJson();
  const cardSlugs = cards.map((c) => c.id).filter(Boolean);

  const allSlugs = Array.from(new Set([...pageSlugs, ...cardSlugs])).sort();

  const guides = allSlugs.map((slug) => {
    let words = 0;
    try {
      const html = fs.readFileSync(guidePagePath(slug), 'utf8');
      const body = extractBodyHtml(html);
      words = wordCount(body);
    } catch (e) {
      // no page yet
    }
    const card = cards.find((c) => c.id === slug) || null;
    return {
      slug,
      words,
      hasPage: pageSlugs.includes(slug),
      hasCard: !!card,
      title: card ? card.title : null
    };
  });

  res.json({ guides });
});

// ---- Get a single guide's article HTML + card data ----
router.get('/api/admin/guides/:slug', (req, res) => {
  const { slug } = req.params;
  if (!SLUG_RE.test(slug)) {
    return res.status(400).json({ error: 'Invalid guide slug. Use letters, numbers, and hyphens only.' });
  }

  let bodyHtml = '';
  let isNewPage = true;
  try {
    const html = fs.readFileSync(guidePagePath(slug), 'utf8');
    bodyHtml = extractBodyHtml(html) || '';
    isNewPage = false;
  } catch (e) {
    // no page yet, return empty
  }

  const cards = readGuidesJson();
  const card = cards.find((c) => c.id === slug) || null;

  res.json({ bodyHtml, isNewPage, card, isNewCard: !card });
});

// ---- Save (create or update) a guide's page AND card entry ----
router.put('/api/admin/guides/:slug', express.json({ limit: '2mb' }), (req, res) => {
  const { slug } = req.params;
  if (!SLUG_RE.test(slug)) {
    return res.status(400).json({ error: 'Invalid guide slug. Use letters, numbers, and hyphens only.' });
  }

  const body = req.body || {};
  const card = body.card || {};

  const title = String(card.title || '').trim();
  if (!title) {
    return res.status(400).json({ error: 'Please give the guide a title.' });
  }

  const tagline = String(card.tagline || '').trim();
  const description = String(card.description || '').trim();
  const category = String(card.category || 'Guide').trim();
  const url = `/guides/${slug}/`;

  const bodyHtml = sanitizeBodyHtml(body.bodyHtml || '');

  // ---- write the standalone article page ----
  const pageHtml = renderGuidePage({
    slug, title, tagline, description, category, bodyHtml
  });

  fs.mkdirSync(path.join(GUIDES_DIR, slug), { recursive: true });
  fs.writeFileSync(guidePagePath(slug), pageHtml, 'utf8');

  // ---- upsert the homepage card ----
  const cards = readGuidesJson();
  const idx = cards.findIndex((c) => c.id === slug);
  const entry = { id: slug, title, tagline, description, category, url };

  if (idx >= 0) {
    cards[idx] = entry;
  } else {
    cards.push(entry);
  }
  writeGuidesJson(cards);

  res.json({
    ok: true,
    words: wordCount(bodyHtml),
    url
  });
});

// ---- Delete a guide's page AND its homepage card entry ----
router.delete('/api/admin/guides/:slug', (req, res) => {
  const { slug } = req.params;
  if (!SLUG_RE.test(slug)) {
    return res.status(400).json({ error: 'Invalid guide slug.' });
  }

  let removedAnything = false;

  const dir = path.join(GUIDES_DIR, slug);
  try {
    fs.rmSync(dir, { recursive: true, force: true });
    removedAnything = true;
  } catch (e) {
    // no page, fine
  }

  const cards = readGuidesJson();
  const next = cards.filter((c) => c.id !== slug);
  if (next.length !== cards.length) {
    writeGuidesJson(next);
    removedAnything = true;
  }

  if (!removedAnything) {
    return res.status(404).json({ error: 'Guide not found.' });
  }

  res.json({ ok: true });
});


module.exports = router;
